# Generated by Django 4.1.4 on 2023-01-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='good_category',
        ),
        migrations.AlterField(
            model_name='introduction',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='自己紹介・一言'),
        ),
    ]
