# Generated by Django 4.1.4 on 2023-01-06 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_connection_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='following',
        ),
        migrations.AlterField(
            model_name='connection',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
