# Generated by Django 4.1.4 on 2023-01-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_connection_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='follower',
            field=models.CharField(max_length=20),
        ),
    ]
