# Generated by Django 4.1.4 on 2023-01-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_connection_follower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
